reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "users#index"

  resources :users, only: [:new, :create, :index, :show]
  resource :session, only: [:new, :create, :destroy]
end

reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :bigint
#  sub_id     :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
    validates :title, presence: true

    belongs_to :sub,
        primary_key: :id,
        foreign_key: :sub_id,
        class_name: :Sub

    belongs_to :author,
        primary_key: :id,
        foreign_key: :author_id,
        class_name: :User
end

reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  description  :text
#  moderator_id :bigint
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Sub < ApplicationRecord
    validates :title, presence: true
    
    belongs_to :moderator,
        primary_key: :id,
        foreign_key: :moderator_id,
        class_name: :User

    has_many :posts,
        primary_key: :id,
        foreign_key: :sub_id,
        class_name: :Post

    
        
end

reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
# + Within User Class
# + F => ::find_by_credentials(username, password)
# + I => #is_password?(password)
# + G => #generate_session_token
# + V => #validations
# + A => #attr_reader :password
# + P => #password=(password)
# + E => #ensure_session_token
# + B => #before_validation (ensure_session_token)
# + R => #reset_session_token!
    before_validation :ensure_session_token

    has_many :subs,
        primary_key: :id,
        foreign_key: :moderator_id,
        class_name: :Sub

    has_many posts:
        through: :subs,
        source: :posts


    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        if user && user.is_password?(password)
            user
        else
            nil
        end
    end

    def is_password?(password)
        pass_obj = BCrypt::Password.new(self.password_digest)
        pass_obj.is_password?(password)
    end

    def generate_session_token
        SecureRandom::urlsafe_base64
    end

    validates :username, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: { minimum: 6 }, allow_nil: true

    attr_reader :password

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def ensure_session_token
        self.session_token ||= generate_session_token
    end

    def reset_session_token!
        self.session_token = generate_session_token
        self.save!
        self.session_token
    end
end

reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # + Within Application Controller
    # + C => #current_user
    # + R => #require_logged_in, #require_logged_out
    # + L => #logged_in?
    # + L => #login(user)
    # + L => #logout!
    #helper_method
    helper_method :current_user, :logged_in?

    def current_user
        current_session_token = session[:session_token]
        @current_user ||= User.find_by(session_token: current_session_token)
    end

    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def require_logged_out
        redirect_to users_url if logged_in?
    end

    def logged_in?
        !!current_user
    end

    def login(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout!
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end
    
end

reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_logged_in, only: [:destroy]
    before_action :require_logged_out, only: [:new, :create]
    def new
        @user = User.new
        render :new
    end

    def create
        username = params[:user][:username]
        password = params[:user][:password]

        user = User.find_by_credentials(username, password)

        if user.nil?
            @user = User.new(username: username)
            render :new
        else
            login(user)
            redirect_to user_url(user)
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end
end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_logged_in, only: [:show, :index]
    before_action :require_logged_out, only: [:new, :create]

    def new
        @user = User.new
        render :new
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    def create
        @user = User.new(user_params)
        
        if @user.save
            login(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors]= @user.errors.full_messages
            render :new
        end
    end

    def index
        @users = User.all
        render :index
    end

    private 
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
    def auth_token
        "<input type = 'hidden' name= 'authenticity_token' value='#{form_authenticity_token}'/>.html_safe"
    end
end

reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
      <% if logged_in? %>
        <nav>
          <a class='button' href="<%= users_url %>">Take me Home</a>
          
          <div class='user-detail'>
            <p>Logged in as: <%= current_user.username %></p>
          <form action=<%= session_url %> method='post'>
            <input
              type="hidden"
              name="_method"
              value="delete">
            <input
              type="hidden"
              name="authenticity_token"
              value="<%= form_authenticity_token %>">
            <input 
              type="submit" value="Sign Out">
          </form>
          </div>
        </nav>
      <% end %>

    <%= yield %>
  </body>
</html>

reddit_clone/app/views/users/index.html.erb
<h1>All Users</h1>
<ul>
    <%@users.each do |user|%>
        <li><a href="<%=user_url(user)%>"><%=user.username%></a></li>
    <%end%>
</ul>

reddit_clone/app/views/users/new.html.erb
<h1> Sign Up Page </h1>

<form action="<%= users_url %>" method="POST">
<input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
<p>
<label for='username'>Username:</label>
<input id='username' type='text' name='user[username]' value="<%=@user.username%>">
</p>

<p>
<label for='password'>Password:</label>
<input id='password' type='password' name='user[password]' value=''>
</p>

<input type="submit" value="Sign Up">
</form>

reddit_clone/app/views/users/show.html.erb
<h1>Logged in as: "<%=@user.username%>"</h1>